apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: semiconductor-ops-data
  labels:
    app: semiconductor-ops-platform
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
